#!/usr/bin/env ruby

require 'vault'

source = JSON.parse ARGF.read

host = source['source']['host']
token = source['source']['token']
secret = source['source']['secret']

Vault.configure do |config|
  config.address = host
  config.token = token
  config.ssl_verify = false
end

dataobj = Vault.logical.read secret

begin
  version = dataobj.data[:metadata][:version]
rescue
  version = Time.now.to_i
end

ret = []
ret << {id: "#{version}"}

puts ret.to_json
